services:
  api:
    env_file:
      - ./server/.env
    build:
      context: ./server
      dockerfile: ./Dockerfile
    volumes:
      - ./server:/app
      - api_tmp:/app/tmp

    ports:
      - "8000:8000"
    command: ["air", "-c", ".air.toml"]
    restart: always 
    depends_on:
      - db
  db:
    env_file:
      - ./server/.env
    image: postgres:17-alpine
    ports: 
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    env_file:
      - ./client/.env
    restart: always
volumes:
  postgres_data:
  api_tmp: