FROM golang:1.24.2-alpine AS builder

WORKDIR /app

COPY go.* ./

RUN go mod download

COPY . ./

RUN go build -o app ./cmd/api

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/app .

EXPOSE 8000

CMD [ "./app" ]
